/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const APEPRole = IDL.Variant({
  'hod' : IDL.Null,
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : APEPRole,
  'email' : IDL.Text,
});
export const AssignmentSubmission = IDL.Record({
  'id' : IDL.Text,
  'studentId' : IDL.Principal,
  'file' : ExternalBlob,
  'submittedAt' : IDL.Int,
  'assignmentId' : IDL.Text,
});
export const RecheckRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'studentId' : IDL.Principal,
  'answerSheetId' : IDL.Text,
  'createdAt' : IDL.Int,
  'teacherNote' : IDL.Opt(IDL.Text),
  'reason' : IDL.Text,
});
export const AttendanceRecord = IDL.Record({
  'status' : IDL.Variant({
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  }),
  'studentId' : IDL.Principal,
  'date' : IDL.Text,
  'subjectId' : IDL.Text,
});
export const InternalMark = IDL.Record({
  'studentId' : IDL.Principal,
  'subjectId' : IDL.Text,
  'maxMarks' : IDL.Nat,
  'obtainedMarks' : IDL.Nat,
  'examType' : IDL.Text,
});
export const Notice = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'postedBy' : IDL.Principal,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'subjectId' : IDL.Opt(IDL.Text),
  'targetRole' : IDL.Variant({
    'all' : IDL.Null,
    'teacher' : IDL.Null,
    'student' : IDL.Null,
  }),
});
export const Subject = IDL.Record({
  'id' : IDL.Text,
  'semester' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'teacherId' : IDL.Principal,
});
export const Assignment = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'postedBy' : IDL.Principal,
  'file' : ExternalBlob,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'subjectId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignStudentToSubject' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'createAssignment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createStudentProfile' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'createSubject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createTeacherProfile' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'createUserProfile' : IDL.Func(
      [IDL.Principal, APEPRole, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteUserProfile' : IDL.Func([IDL.Principal], [], []),
  'getAllStudents' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAssignmentSubmissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AssignmentSubmission)],
      ['query'],
    ),
  'getAttendanceShortageReport' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRecheckRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RecheckRequest)],
      ['query'],
    ),
  'getStudentAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getStudentMarks' : IDL.Func([IDL.Text], [IDL.Vec(InternalMark)], ['query']),
  'getStudentNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getStudentSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getSubjectAssignments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getSubjectPerformanceStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getSystemStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'teacherCount' : IDL.Nat,
          'subjectCount' : IDL.Nat,
          'studentCount' : IDL.Nat,
          'userCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTeacherSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSampleData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func(
      [
        IDL.Text,
        IDL.Principal,
        IDL.Text,
        IDL.Variant({
          'present' : IDL.Null,
          'late' : IDL.Null,
          'absent' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'postDepartmentNotice' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'all' : IDL.Null,
          'teacher' : IDL.Null,
          'student' : IDL.Null,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'postSubjectNotice' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'all' : IDL.Null,
          'teacher' : IDL.Null,
          'student' : IDL.Null,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'requestRecheck' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'respondToRecheckRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({ 'approved' : IDL.Null, 'rejected' : IDL.Null }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAssignment' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Principal, APEPRole, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'uploadAnswerSheet' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal, ExternalBlob],
      [IDL.Text],
      [],
    ),
  'uploadInternalMarks' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const APEPRole = IDL.Variant({
    'hod' : IDL.Null,
    'admin' : IDL.Null,
    'teacher' : IDL.Null,
    'student' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : APEPRole,
    'email' : IDL.Text,
  });
  const AssignmentSubmission = IDL.Record({
    'id' : IDL.Text,
    'studentId' : IDL.Principal,
    'file' : ExternalBlob,
    'submittedAt' : IDL.Int,
    'assignmentId' : IDL.Text,
  });
  const RecheckRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'studentId' : IDL.Principal,
    'answerSheetId' : IDL.Text,
    'createdAt' : IDL.Int,
    'teacherNote' : IDL.Opt(IDL.Text),
    'reason' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'status' : IDL.Variant({
      'present' : IDL.Null,
      'late' : IDL.Null,
      'absent' : IDL.Null,
    }),
    'studentId' : IDL.Principal,
    'date' : IDL.Text,
    'subjectId' : IDL.Text,
  });
  const InternalMark = IDL.Record({
    'studentId' : IDL.Principal,
    'subjectId' : IDL.Text,
    'maxMarks' : IDL.Nat,
    'obtainedMarks' : IDL.Nat,
    'examType' : IDL.Text,
  });
  const Notice = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'postedBy' : IDL.Principal,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'subjectId' : IDL.Opt(IDL.Text),
    'targetRole' : IDL.Variant({
      'all' : IDL.Null,
      'teacher' : IDL.Null,
      'student' : IDL.Null,
    }),
  });
  const Subject = IDL.Record({
    'id' : IDL.Text,
    'semester' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'teacherId' : IDL.Principal,
  });
  const Assignment = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'postedBy' : IDL.Principal,
    'file' : ExternalBlob,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'subjectId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignStudentToSubject' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'createAssignment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createStudentProfile' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'createSubject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createTeacherProfile' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'createUserProfile' : IDL.Func(
        [IDL.Principal, APEPRole, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteUserProfile' : IDL.Func([IDL.Principal], [], []),
    'getAllStudents' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAssignmentSubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AssignmentSubmission)],
        ['query'],
      ),
    'getAttendanceShortageReport' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRecheckRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RecheckRequest)],
        ['query'],
      ),
    'getStudentAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getStudentMarks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(InternalMark)],
        ['query'],
      ),
    'getStudentNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getStudentSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getSubjectAssignments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getSubjectPerformanceStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getSystemStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'teacherCount' : IDL.Nat,
            'subjectCount' : IDL.Nat,
            'studentCount' : IDL.Nat,
            'userCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTeacherSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSampleData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func(
        [
          IDL.Text,
          IDL.Principal,
          IDL.Text,
          IDL.Variant({
            'present' : IDL.Null,
            'late' : IDL.Null,
            'absent' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'postDepartmentNotice' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'all' : IDL.Null,
            'teacher' : IDL.Null,
            'student' : IDL.Null,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'postSubjectNotice' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'all' : IDL.Null,
            'teacher' : IDL.Null,
            'student' : IDL.Null,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'requestRecheck' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'respondToRecheckRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({ 'approved' : IDL.Null, 'rejected' : IDL.Null }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAssignment' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
    'updateUserProfile' : IDL.Func(
        [IDL.Principal, APEPRole, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'uploadAnswerSheet' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal, ExternalBlob],
        [IDL.Text],
        [],
      ),
    'uploadInternalMarks' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };