/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type APEPRole = { 'hod' : null } |
  { 'admin' : null } |
  { 'teacher' : null } |
  { 'student' : null };
export interface Assignment {
  'id' : string,
  'title' : string,
  'postedBy' : Principal,
  'file' : ExternalBlob,
  'createdAt' : bigint,
  'dueDate' : string,
  'description' : string,
  'subjectId' : string,
}
export interface AssignmentSubmission {
  'id' : string,
  'studentId' : Principal,
  'file' : ExternalBlob,
  'submittedAt' : bigint,
  'assignmentId' : string,
}
export interface AttendanceRecord {
  'status' : { 'present' : null } |
    { 'late' : null } |
    { 'absent' : null },
  'studentId' : Principal,
  'date' : string,
  'subjectId' : string,
}
export type ExternalBlob = Uint8Array;
export interface InternalMark {
  'studentId' : Principal,
  'subjectId' : string,
  'maxMarks' : bigint,
  'obtainedMarks' : bigint,
  'examType' : string,
}
export interface Notice {
  'id' : string,
  'title' : string,
  'postedBy' : Principal,
  'content' : string,
  'createdAt' : bigint,
  'subjectId' : [] | [string],
  'targetRole' : { 'all' : null } |
    { 'teacher' : null } |
    { 'student' : null },
}
export interface RecheckRequest {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'studentId' : Principal,
  'answerSheetId' : string,
  'createdAt' : bigint,
  'teacherNote' : [] | [string],
  'reason' : string,
}
export interface Subject {
  'id' : string,
  'semester' : bigint,
  'code' : string,
  'name' : string,
  'section' : string,
  'teacherId' : Principal,
}
export interface UserProfile {
  'userId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'role' : APEPRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignStudentToSubject' : ActorMethod<[Principal, string], undefined>,
  'createAssignment' : ActorMethod<
    [string, string, string, ExternalBlob, string],
    string
  >,
  'createStudentProfile' : ActorMethod<
    [Principal, string, string, bigint, string],
    undefined
  >,
  'createSubject' : ActorMethod<
    [string, string, Principal, bigint, string],
    string
  >,
  'createTeacherProfile' : ActorMethod<
    [Principal, string, Array<string>],
    undefined
  >,
  'createUserProfile' : ActorMethod<
    [Principal, APEPRole, string, string],
    undefined
  >,
  'deleteUserProfile' : ActorMethod<[Principal], undefined>,
  'getAllStudents' : ActorMethod<[], Array<UserProfile>>,
  'getAllTeachers' : ActorMethod<[], Array<UserProfile>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAssignmentSubmissions' : ActorMethod<
    [string],
    Array<AssignmentSubmission>
  >,
  'getAttendanceShortageReport' : ActorMethod<
    [bigint],
    Array<[Principal, string, bigint]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRecheckRequests' : ActorMethod<[string], Array<RecheckRequest>>,
  'getStudentAttendance' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getStudentMarks' : ActorMethod<[string], Array<InternalMark>>,
  'getStudentNotices' : ActorMethod<[], Array<Notice>>,
  'getStudentSubjects' : ActorMethod<[], Array<Subject>>,
  'getSubjectAssignments' : ActorMethod<[string], Array<Assignment>>,
  'getSubjectPerformanceStats' : ActorMethod<[], Array<[string, bigint]>>,
  'getSystemStats' : ActorMethod<
    [],
    {
      'teacherCount' : bigint,
      'subjectCount' : bigint,
      'studentCount' : bigint,
      'userCount' : bigint,
    }
  >,
  'getTeacherSubjects' : ActorMethod<[], Array<Subject>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSampleData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<
    [
      string,
      Principal,
      string,
      { 'present' : null } |
        { 'late' : null } |
        { 'absent' : null },
    ],
    undefined
  >,
  'postDepartmentNotice' : ActorMethod<
    [
      string,
      string,
      { 'all' : null } |
        { 'teacher' : null } |
        { 'student' : null },
    ],
    string
  >,
  'postSubjectNotice' : ActorMethod<
    [
      string,
      string,
      string,
      { 'all' : null } |
        { 'teacher' : null } |
        { 'student' : null },
    ],
    string
  >,
  'requestRecheck' : ActorMethod<[string, string], string>,
  'respondToRecheckRequest' : ActorMethod<
    [string, { 'approved' : null } | { 'rejected' : null }, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAssignment' : ActorMethod<[string, ExternalBlob], string>,
  'updateUserProfile' : ActorMethod<
    [Principal, APEPRole, string, string],
    undefined
  >,
  'uploadAnswerSheet' : ActorMethod<
    [string, string, Principal, ExternalBlob],
    string
  >,
  'uploadInternalMarks' : ActorMethod<
    [string, Principal, string, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];