/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AssignmentSubmission {
    id: string;
    studentId: Principal;
    file: ExternalBlob;
    submittedAt: bigint;
    assignmentId: string;
}
export interface RecheckRequest {
    id: string;
    status: Variant_pending_approved_rejected;
    studentId: Principal;
    answerSheetId: string;
    createdAt: bigint;
    teacherNote?: string;
    reason: string;
}
export interface Notice {
    id: string;
    title: string;
    postedBy: Principal;
    content: string;
    createdAt: bigint;
    subjectId?: string;
    targetRole: Variant_all_teacher_student;
}
export interface Assignment {
    id: string;
    title: string;
    postedBy: Principal;
    file: ExternalBlob;
    createdAt: bigint;
    dueDate: string;
    description: string;
    subjectId: string;
}
export interface AttendanceRecord {
    status: Variant_present_late_absent;
    studentId: Principal;
    date: string;
    subjectId: string;
}
export interface InternalMark {
    studentId: Principal;
    subjectId: string;
    maxMarks: bigint;
    obtainedMarks: bigint;
    examType: string;
}
export interface Subject {
    id: string;
    semester: bigint;
    code: string;
    name: string;
    section: string;
    teacherId: Principal;
}
export interface UserProfile {
    userId: Principal;
    name: string;
    createdAt: bigint;
    role: APEPRole;
    email: string;
}
export enum APEPRole {
    hod = "hod",
    admin = "admin",
    teacher = "teacher",
    student = "student"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_all_teacher_student {
    all = "all",
    teacher = "teacher",
    student = "student"
}
export enum Variant_approved_rejected {
    approved = "approved",
    rejected = "rejected"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Variant_present_late_absent {
    present = "present",
    late = "late",
    absent = "absent"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignStudentToSubject(studentId: Principal, subjectId: string): Promise<void>;
    createAssignment(subjectId: string, title: string, description: string, file: ExternalBlob, dueDate: string): Promise<string>;
    createStudentProfile(userId: Principal, rollNumber: string, course: string, semester: bigint, section: string): Promise<void>;
    createSubject(name: string, code: string, teacherId: Principal, semester: bigint, section: string): Promise<string>;
    createTeacherProfile(userId: Principal, teacherCode: string, subjectIds: Array<string>): Promise<void>;
    createUserProfile(userId: Principal, role: APEPRole, name: string, email: string): Promise<void>;
    deleteUserProfile(userId: Principal): Promise<void>;
    getAllStudents(): Promise<Array<UserProfile>>;
    getAllTeachers(): Promise<Array<UserProfile>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getAssignmentSubmissions(assignmentId: string): Promise<Array<AssignmentSubmission>>;
    getAttendanceShortageReport(threshold: bigint): Promise<Array<[Principal, string, bigint]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getRecheckRequests(subjectId: string): Promise<Array<RecheckRequest>>;
    getStudentAttendance(subjectId: string): Promise<Array<AttendanceRecord>>;
    getStudentMarks(subjectId: string): Promise<Array<InternalMark>>;
    getStudentNotices(): Promise<Array<Notice>>;
    getStudentSubjects(): Promise<Array<Subject>>;
    getSubjectAssignments(subjectId: string): Promise<Array<Assignment>>;
    getSubjectPerformanceStats(): Promise<Array<[string, bigint]>>;
    getSystemStats(): Promise<{
        teacherCount: bigint;
        subjectCount: bigint;
        studentCount: bigint;
        userCount: bigint;
    }>;
    getTeacherSubjects(): Promise<Array<Subject>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeSampleData(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markAttendance(subjectId: string, studentId: Principal, date: string, status: Variant_present_late_absent): Promise<void>;
    postDepartmentNotice(title: string, content: string, targetRole: Variant_all_teacher_student): Promise<string>;
    postSubjectNotice(subjectId: string, title: string, content: string, targetRole: Variant_all_teacher_student): Promise<string>;
    requestRecheck(answerSheetId: string, reason: string): Promise<string>;
    respondToRecheckRequest(requestId: string, status: Variant_approved_rejected, teacherNote: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitAssignment(assignmentId: string, file: ExternalBlob): Promise<string>;
    updateUserProfile(userId: Principal, role: APEPRole, name: string, email: string): Promise<void>;
    uploadAnswerSheet(subjectId: string, examType: string, studentId: Principal, file: ExternalBlob): Promise<string>;
    uploadInternalMarks(subjectId: string, studentId: Principal, examType: string, maxMarks: bigint, obtainedMarks: bigint): Promise<void>;
}
import type { APEPRole as _APEPRole, Assignment as _Assignment, AssignmentSubmission as _AssignmentSubmission, AttendanceRecord as _AttendanceRecord, ExternalBlob as _ExternalBlob, Notice as _Notice, RecheckRequest as _RecheckRequest, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignStudentToSubject(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignStudentToSubject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignStudentToSubject(arg0, arg1);
            return result;
        }
    }
    async createAssignment(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssignment(arg0, arg1, arg2, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssignment(arg0, arg1, arg2, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async createStudentProfile(arg0: Principal, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudentProfile(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudentProfile(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createSubject(arg0: string, arg1: string, arg2: Principal, arg3: bigint, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubject(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubject(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createTeacherProfile(arg0: Principal, arg1: string, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeacherProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeacherProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async createUserProfile(arg0: Principal, arg1: APEPRole, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(arg0, to_candid_APEPRole_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(arg0, to_candid_APEPRole_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async deleteUserProfile(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserProfile(arg0);
            return result;
        }
    }
    async getAllStudents(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeachers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeachers();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeachers();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssignmentSubmissions(arg0: string): Promise<Array<AssignmentSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignmentSubmissions(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignmentSubmissions(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceShortageReport(arg0: bigint): Promise<Array<[Principal, string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceShortageReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceShortageReport(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecheckRequests(arg0: string): Promise<Array<RecheckRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecheckRequests(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecheckRequests(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentAttendance(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentAttendance(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentAttendance(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentMarks(arg0: string): Promise<Array<InternalMark>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentMarks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentMarks(arg0);
            return result;
        }
    }
    async getStudentNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentNotices();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentNotices();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentSubjects();
            return result;
        }
    }
    async getSubjectAssignments(arg0: string): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectAssignments(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectAssignments(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjectPerformanceStats(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectPerformanceStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectPerformanceStats();
            return result;
        }
    }
    async getSystemStats(): Promise<{
        teacherCount: bigint;
        subjectCount: bigint;
        studentCount: bigint;
        userCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemStats();
            return result;
        }
    }
    async getTeacherSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherSubjects();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeSampleData();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAttendance(arg0: string, arg1: Principal, arg2: string, arg3: Variant_present_late_absent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, arg1, arg2, to_candid_variant_n41(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, arg1, arg2, to_candid_variant_n41(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async postDepartmentNotice(arg0: string, arg1: string, arg2: Variant_all_teacher_student): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.postDepartmentNotice(arg0, arg1, to_candid_variant_n42(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postDepartmentNotice(arg0, arg1, to_candid_variant_n42(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async postSubjectNotice(arg0: string, arg1: string, arg2: string, arg3: Variant_all_teacher_student): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.postSubjectNotice(arg0, arg1, arg2, to_candid_variant_n42(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postSubjectNotice(arg0, arg1, arg2, to_candid_variant_n42(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async requestRecheck(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestRecheck(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestRecheck(arg0, arg1);
            return result;
        }
    }
    async respondToRecheckRequest(arg0: string, arg1: Variant_approved_rejected, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToRecheckRequest(arg0, to_candid_variant_n43(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToRecheckRequest(arg0, to_candid_variant_n43(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitAssignment(arg0: string, arg1: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssignment(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssignment(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUserProfile(arg0: Principal, arg1: APEPRole, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, to_candid_APEPRole_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, to_candid_APEPRole_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async uploadAnswerSheet(arg0: string, arg1: string, arg2: Principal, arg3: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadAnswerSheet(arg0, arg1, arg2, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadAnswerSheet(arg0, arg1, arg2, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async uploadInternalMarks(arg0: string, arg1: Principal, arg2: string, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadInternalMarks(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadInternalMarks(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_APEPRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _APEPRole): APEPRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_AssignmentSubmission_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentSubmission): Promise<AssignmentSubmission> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_Assignment_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assignment): Promise<Assignment> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceRecord_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Notice_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notice): Notice {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_RecheckRequest_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecheckRequest): RecheckRequest {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: Principal;
    name: string;
    createdAt: bigint;
    role: _APEPRole;
    email: string;
}): {
    userId: Principal;
    name: string;
    createdAt: bigint;
    role: APEPRole;
    email: string;
} {
    return {
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_APEPRole_n16(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    studentId: Principal;
    file: _ExternalBlob;
    submittedAt: bigint;
    assignmentId: string;
}): Promise<{
    id: string;
    studentId: Principal;
    file: ExternalBlob;
    submittedAt: bigint;
    assignmentId: string;
}> {
    return {
        id: value.id,
        studentId: value.studentId,
        file: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.file),
        submittedAt: value.submittedAt,
        assignmentId: value.assignmentId
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    studentId: Principal;
    answerSheetId: string;
    createdAt: bigint;
    teacherNote: [] | [string];
    reason: string;
}): {
    id: string;
    status: Variant_pending_approved_rejected;
    studentId: Principal;
    answerSheetId: string;
    createdAt: bigint;
    teacherNote?: string;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n28(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        answerSheetId: value.answerSheetId,
        createdAt: value.createdAt,
        teacherNote: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.teacherNote)),
        reason: value.reason
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        present: null;
    } | {
        late: null;
    } | {
        absent: null;
    };
    studentId: Principal;
    date: string;
    subjectId: string;
}): {
    status: Variant_present_late_absent;
    studentId: Principal;
    date: string;
    subjectId: string;
} {
    return {
        status: from_candid_variant_n33(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        subjectId: value.subjectId
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    postedBy: Principal;
    content: string;
    createdAt: bigint;
    subjectId: [] | [string];
    targetRole: {
        all: null;
    } | {
        teacher: null;
    } | {
        student: null;
    };
}): {
    id: string;
    title: string;
    postedBy: Principal;
    content: string;
    createdAt: bigint;
    subjectId?: string;
    targetRole: Variant_all_teacher_student;
} {
    return {
        id: value.id,
        title: value.title,
        postedBy: value.postedBy,
        content: value.content,
        createdAt: value.createdAt,
        subjectId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.subjectId)),
        targetRole: from_candid_variant_n37(_uploadFile, _downloadFile, value.targetRole)
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    postedBy: Principal;
    file: _ExternalBlob;
    createdAt: bigint;
    dueDate: string;
    description: string;
    subjectId: string;
}): Promise<{
    id: string;
    title: string;
    postedBy: Principal;
    file: ExternalBlob;
    createdAt: bigint;
    dueDate: string;
    description: string;
    subjectId: string;
}> {
    return {
        id: value.id,
        title: value.title,
        postedBy: value.postedBy,
        file: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.file),
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        description: value.description,
        subjectId: value.subjectId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hod: null;
} | {
    admin: null;
} | {
    teacher: null;
} | {
    student: null;
}): APEPRole {
    return "hod" in value ? APEPRole.hod : "admin" in value ? APEPRole.admin : "teacher" in value ? APEPRole.teacher : "student" in value ? APEPRole.student : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    late: null;
} | {
    absent: null;
}): Variant_present_late_absent {
    return "present" in value ? Variant_present_late_absent.present : "late" in value ? Variant_present_late_absent.late : "absent" in value ? Variant_present_late_absent.absent : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    teacher: null;
} | {
    student: null;
}): Variant_all_teacher_student {
    return "all" in value ? Variant_all_teacher_student.all : "teacher" in value ? Variant_all_teacher_student.teacher : "student" in value ? Variant_all_teacher_student.student : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n14(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssignmentSubmission>): Promise<Array<AssignmentSubmission>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AssignmentSubmission_n19(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecheckRequest>): Array<RecheckRequest> {
    return value.map((x)=>from_candid_RecheckRequest_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notice>): Array<Notice> {
    return value.map((x)=>from_candid_Notice_n35(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assignment>): Promise<Array<Assignment>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Assignment_n39(_uploadFile, _downloadFile, x)));
}
function to_candid_APEPRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: APEPRole): _APEPRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: Principal;
    name: string;
    createdAt: bigint;
    role: APEPRole;
    email: string;
}): {
    userId: Principal;
    name: string;
    createdAt: bigint;
    role: _APEPRole;
    email: string;
} {
    return {
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_APEPRole_n11(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: APEPRole): {
    hod: null;
} | {
    admin: null;
} | {
    teacher: null;
} | {
    student: null;
} {
    return value == APEPRole.hod ? {
        hod: null
    } : value == APEPRole.admin ? {
        admin: null
    } : value == APEPRole.teacher ? {
        teacher: null
    } : value == APEPRole.student ? {
        student: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_present_late_absent): {
    present: null;
} | {
    late: null;
} | {
    absent: null;
} {
    return value == Variant_present_late_absent.present ? {
        present: null
    } : value == Variant_present_late_absent.late ? {
        late: null
    } : value == Variant_present_late_absent.absent ? {
        absent: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_all_teacher_student): {
    all: null;
} | {
    teacher: null;
} | {
    student: null;
} {
    return value == Variant_all_teacher_student.all ? {
        all: null
    } : value == Variant_all_teacher_student.teacher ? {
        teacher: null
    } : value == Variant_all_teacher_student.student ? {
        student: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_approved_rejected): {
    approved: null;
} | {
    rejected: null;
} {
    return value == Variant_approved_rejected.approved ? {
        approved: null
    } : value == Variant_approved_rejected.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
